language: ruby
rvm:
  - 2.4.1
  - 2.5
  - 2.6

before_install:
  - gem install bundler
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar -xvf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - export PATH=$PATH:$PWD/wkhtmltox/bin/
