language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7

before_install:
  - gem install bundler
  - sudo apt-get install xfonts-75dpi xfonts-base
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo apt install ./wkhtmltox_0.12.5-1.xenial_amd64.deb
